services:
  - type: web
    name: codeedge-app
    env: docker
    plan: starter
    port: 8080
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:file:/var/lib/codeedge/data/codeedgedb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
    disk:
      name: codeedge-db-disk
      mountPath: /var/lib/codeedge/data
      sizeGB: 1
